application:
  name: meilisearch
  project: meilisearch-example
  organization: STUDENT9901
  storage:
  - name: meili-data
    type: fast_ssd
    size: 10GB
    mount_point: /data.ms
routers:
- name: meili-router
  routes:
  - application_name: meilisearch
    paths:
    - "/"
